package dart

import (
	"strings"

	"github.com/xseman/openapi-generator/internal/codegen"
	"github.com/xseman/openapi-generator/internal/generator"
)

// FetchGenerator implements the dart-fetch generator.
//
// It produces a Dart client with no third-party runtime dependencies.
// HTTP requests are dispatched through a pluggable HttpSender; a
// dart:io HttpClient adapter is included by default.
type FetchGenerator struct {
	*BaseGenerator

	PubName         string
	PubVersion      string
	PubDescription  string
	PubAuthor       string
	PubHomepage     string
	PubRepository   string
	SdkConstraint   string
	UseDartIoSender bool
}

// NewFetchGenerator creates a new Dart Fetch generator.
func NewFetchGenerator() *FetchGenerator {
	base := NewBaseGenerator()
	g := &FetchGenerator{
		BaseGenerator:   base,
		PubName:         "openapi",
		PubVersion:      "1.0.0",
		PubDescription:  "OpenAPI client generated by openapi-generator",
		SdkConstraint:   ">=3.0.0 <4.0.0",
		UseDartIoSender: true,
	}

	g.ApiTemplateFiles["apis.mustache"] = ".dart"
	g.ModelTemplateFiles["models.mustache"] = ".dart"

	g.addExtraReservedWords()
	return g
}

// GetName returns the generator name.
func (g *FetchGenerator) GetName() string { return "dart-fetch" }

// GetTag returns the generator type.
func (g *FetchGenerator) GetTag() generator.GeneratorType { return generator.GeneratorTypeClient }

// GetHelp returns the help text.
func (g *FetchGenerator) GetHelp() string {
	return "Generates a Dart client library with no third-party runtime dependencies."
}

// ProcessOpts processes options and initializes the generator.
func (g *FetchGenerator) ProcessOpts() error {
	if g.DartConfig != nil {
		if g.DartConfig.PubName != "" {
			g.PubName = g.DartConfig.PubName
		}
		if g.DartConfig.PubVersion != "" {
			g.PubVersion = g.DartConfig.PubVersion
		}
		if g.DartConfig.PubDescription != "" {
			g.PubDescription = g.DartConfig.PubDescription
		}
		g.PubAuthor = g.DartConfig.PubAuthor
		g.PubHomepage = g.DartConfig.PubHomepage
		g.PubRepository = g.DartConfig.PubRepository
		if g.DartConfig.SdkConstraint != "" {
			g.SdkConstraint = g.DartConfig.SdkConstraint
		}
		g.UseDartIoSender = g.DartConfig.UseDartIoSender
	}

	g.PubName = sanitizePubName(g.PubName)

	g.SourceDir = ""
	g.ApiPackage = "lib/src/apis"
	g.ModelPackage = "lib/src/models"

	g.AdditionalProperties["pubName"] = g.PubName
	g.AdditionalProperties["pubVersion"] = g.PubVersion
	g.AdditionalProperties["pubDescription"] = g.PubDescription
	g.AdditionalProperties["pubAuthor"] = g.PubAuthor
	g.AdditionalProperties["pubHomepage"] = g.PubHomepage
	g.AdditionalProperties["pubRepository"] = g.PubRepository
	g.AdditionalProperties["sdkConstraint"] = g.SdkConstraint
	g.AdditionalProperties["useDartIoSender"] = g.UseDartIoSender

	g.SupportingFiles = append(g.SupportingFiles,
		generator.NewSupportingFile("library.mustache", "lib", g.PubName+".dart"),
		generator.NewSupportingFile("runtime.mustache", "lib/src", "runtime.dart"),
		generator.NewSupportingFile("pubspec.mustache", "", "pubspec.yaml"),
		generator.NewSupportingFile("analysis_options.mustache", "", "analysis_options.yaml"),
		generator.NewSupportingFile("gitignore.mustache", "", ".gitignore"),
		generator.NewSupportingFile("README.mustache", "", "README.md"),
	)

	return nil
}

// PostProcessModels translates TypeScript-shaped DataType strings emitted by
// the parser into Dart equivalents and computes per-property serialization
// metadata used by the model template.
func (g *FetchGenerator) PostProcessModels(models []*codegen.CodegenModel) []*codegen.CodegenModel {
	for _, m := range models {
		m.DataType = g.translateType(m.DataType)
		for _, v := range m.Vars {
			g.translateProperty(v)
		}
		for _, v := range m.AllVars {
			g.translateProperty(v)
		}
		for _, v := range m.RequiredVars {
			g.translateProperty(v)
		}
		for _, v := range m.OptionalVars {
			g.translateProperty(v)
		}
		if m.Items != nil {
			g.translateProperty(m.Items)
		}
	}
	return models
}

// PostProcessOperations translates TypeScript-shaped types on operations and
// their parameters, and escapes operation IDs that conflict with Dart keywords
// or with the *Raw method-naming convention used by the apis template.
func (g *FetchGenerator) PostProcessOperations(ops []*codegen.CodegenOperation) []*codegen.CodegenOperation {
	for _, op := range ops {
		op.ReturnType = g.translateType(op.ReturnType)
		op.ReturnBaseType = g.translateType(op.ReturnBaseType)
		if op.ReturnProperty != nil {
			g.translateProperty(op.ReturnProperty)
		}
		for _, p := range op.AllParams {
			g.translateParameter(p)
		}
		for _, p := range op.BodyParams {
			g.translateParameter(p)
		}
		for _, p := range op.PathParams {
			g.translateParameter(p)
		}
		for _, p := range op.QueryParams {
			g.translateParameter(p)
		}
		for _, p := range op.HeaderParams {
			g.translateParameter(p)
		}
		for _, p := range op.FormParams {
			g.translateParameter(p)
		}
		if op.BodyParam != nil {
			g.translateParameter(op.BodyParam)
		}
		g.escapeOperationId(op)
	}
	return ops
}

// translateProperty rewrites DataType and BaseType to Dart and recurses into
// any nested Items / AdditionalProperties.
func (g *FetchGenerator) translateProperty(p *codegen.CodegenProperty) {
	if p == nil {
		return
	}
	if p.Items != nil {
		g.translateProperty(p.Items)
	}
	if p.AdditionalProperties != nil {
		g.translateProperty(p.AdditionalProperties)
	}
	if p.MostInnerItems != nil {
		g.translateProperty(p.MostInnerItems)
	}
	p.DataType = g.translateType(p.DataType)
	p.Datatype = p.DataType
	p.BaseType = g.translateBaseType(p.BaseType)
	p.DatatypeWithEnum = g.translateType(p.DatatypeWithEnum)
}

func (g *FetchGenerator) translateParameter(p *codegen.CodegenParameter) {
	if p == nil {
		return
	}
	if p.Items != nil {
		g.translateProperty(p.Items)
	}
	if p.AdditionalProperties != nil {
		g.translateProperty(p.AdditionalProperties)
	}
	p.DataType = g.translateType(p.DataType)
	p.BaseType = g.translateBaseType(p.BaseType)
	p.DatatypeWithEnum = g.translateType(p.DatatypeWithEnum)
}

// translateBaseType maps base type names (TypeScript primitives) to Dart.
// Model class names pass through unchanged.
func (g *FetchGenerator) translateBaseType(t string) string {
	switch t {
	case "":
		return ""
	case "any":
		return "Object"
	case "boolean":
		return "bool"
	case "number":
		return "num"
	case "string":
		return "String"
	case "Date":
		return "DateTime"
	case "Blob":
		return "List<int>"
	}
	return t
}

// translateType rewrites a TypeScript-shaped DataType string produced by the
// parser into the equivalent Dart type expression.
//
// Handled forms:
//   - Array<X>                       -> List<X> (recursive)
//   - { [key: string]: X; }          -> Map<String, X> (recursive)
//   - any                            -> Object?
//   - boolean / number / string / Date / Blob -> bool / num / String / DateTime / List<int>
//   - bare model names pass through unchanged.
func (g *FetchGenerator) translateType(t string) string {
	t = strings.TrimSpace(t)
	if t == "" {
		return ""
	}

	// Array<X>
	if strings.HasPrefix(t, "Array<") && strings.HasSuffix(t, ">") {
		inner := t[len("Array<") : len(t)-1]
		return "List<" + g.translateType(inner) + ">"
	}
	// Set<X>
	if strings.HasPrefix(t, "Set<") && strings.HasSuffix(t, ">") {
		inner := t[len("Set<") : len(t)-1]
		return "Set<" + g.translateType(inner) + ">"
	}
	// { [key: string]: X; } or { [key: string]: X }
	if strings.HasPrefix(t, "{") && strings.Contains(t, "[key: string]:") {
		inner := t
		inner = strings.TrimPrefix(inner, "{")
		inner = strings.TrimSuffix(inner, "}")
		inner = strings.TrimSpace(inner)
		inner = strings.TrimPrefix(inner, "[key: string]:")
		inner = strings.TrimSpace(inner)
		inner = strings.TrimSuffix(inner, ";")
		inner = strings.TrimSpace(inner)
		return "Map<String, " + g.translateType(inner) + ">"
	}
	// Union types (TS "A | B") collapse to Object? in Dart for now.
	if strings.Contains(t, " | ") {
		return "Object?"
	}
	switch t {
	case "any":
		return "Object?"
	case "boolean":
		return "bool"
	case "number":
		return "num"
	case "string":
		return "String"
	case "Date":
		return "DateTime"
	case "Blob":
		return "List<int>"
	case "void", "undefined":
		return "void"
	}
	return t
}

// escapeOperationId disambiguates operation method names that would clash
// with the internal `*Raw` / `*RequestOpts` helpers emitted by the api
// template, or that are Dart reserved words.
func (g *FetchGenerator) escapeOperationId(op *codegen.CodegenOperation) {
	if strings.HasSuffix(op.OperationIdCamelCase, "Raw") {
		op.OperationIdCamelCase += "Method"
		op.OperationIdLowerCase += "method"
		op.OperationIdSnakeCase += "_method"
		op.Nickname = op.OperationIdCamelCase
		return
	}
	if g.IsReservedWord(op.Nickname) {
		op.Nickname = op.Nickname + "_"
	}
}

// addExtraReservedWords reserves names used by the generated runtime to
// prevent collisions with model class names.
func (g *FetchGenerator) addExtraReservedWords() {
	extra := []string{
		"BaseApi", "Configuration", "ApiException", "RequiredParameterError",
		"HttpRequest", "HttpResponse", "HttpSender", "HttpMethod",
		"JsonApiResponse", "VoidApiResponse", "TextApiResponse", "BlobApiResponse",
		"Middleware", "RequestContext", "ResponseContext",
		"defaultHttpSender", "encodeFormData", "encodeQueryParam",
	}
	for _, w := range extra {
		g.ReservedWords[strings.ToLower(w)] = true
	}
}

// sanitizePubName ensures the package name is a valid Dart pub package
// identifier: lower_snake_case, starts with a letter, only [a-z0-9_].
func sanitizePubName(name string) string {
	if name == "" {
		return "openapi"
	}
	name = Underscore(name)
	var out strings.Builder
	for i, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			out.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				out.WriteByte('_')
			}
			out.WriteRune(r)
		case r == '_':
			out.WriteRune(r)
		}
	}
	if out.Len() == 0 {
		return "openapi"
	}
	return out.String()
}
